# Generated by Django 5.1 on 2024-08-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_lesson_video_url_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
    ]
