# Generated by Django 5.1 on 2024-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_payment_payment_link_payment_session_id_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                default="transfer",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
